"""
3-Phase Call Orchestrator
==========================
Phase 1: Patient calls → agent takes inquiry → says "I'll call you back in 15 min" → hangs up
Phase 2: AI calls insurance → full back-and-forth conversation → extracts key details
Phase 3: AI calls patient back with natural spoken summary

The insurance conversation is generated by OpenAI to sound natural and varied.
Events are broadcast live to the dashboard with timing delays so it sounds real.
"""

import os
import asyncio
import logging
import httpx
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

logger = logging.getLogger(__name__)

INSURANCE_URL = os.getenv("INSURANCE_AGENT_URL", "http://localhost:8002")
GRAPH_URL     = os.getenv("GRAPH_RAG_URL", "http://localhost:8000")
TWILIO_SID    = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_TOKEN  = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM   = os.getenv("TWILIO_PHONE_NUMBER", "")
OPENAI_KEY    = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL  = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

logger.info("Orchestrator OPENAI_KEY loaded: %s", "YES" if OPENAI_KEY else "NO")


async def _llm(system: str, user: str, temperature: float = 0.8) -> str:
    """Call OpenAI to generate natural conversational text."""
    if not OPENAI_KEY:
        return ""  # empty so caller's `or` fallback triggers
    try:
        from openai import AsyncOpenAI
        client = AsyncOpenAI(api_key=OPENAI_KEY)
        r = await client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[{"role": "system", "content": system},
                      {"role": "user",   "content": user}],
            max_tokens=180,
            temperature=temperature,
        )
        return r.choices[0].message.content.strip()
    except Exception as e:
        logger.error("LLM failed: %s", e)
        return ""  # empty so caller's `or` fallback triggers


async def run_three_phase(
    patient_name:    str,
    callback_number: str,
    inquiry_type:    str,
    call_id:         str,
) -> dict:
    from events import broadcast

    logger.info("[3-PHASE] Starting for %s (type=%s)", patient_name, inquiry_type)

    # ── Wait for first call to fully end ─────────────────────────────────
    await asyncio.sleep(1)

    # ── Get patient data from graph ───────────────────────────────────────
    patient_data = {}
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            ep_map = {"claim_status":"claim-status","cost_estimate":"cost-estimate","pre_procedure":"pre-procedure","bill_explain":"bill-explanation"}
            ep = ep_map.get(inquiry_type, "claim-status")
            r  = await client.post(f"{GRAPH_URL}/hospital/{ep}", json={"patient_name": patient_name})
            patient_data = r.json()
    except Exception as e:
        logger.error("Patient data fetch failed: %s", e)

    claim_answer = patient_data.get("answer", "")

    # ── Phase 2: Hospital agent calls insurance ───────────────────────────
    # Step 1: Dialing
    await broadcast("insurance_calling", {
        "call_id": call_id,
        "patient_name": patient_name,
        "message": f"Dialing Pacific Shield Insurance on behalf of {patient_name}...",
        "speaker": "hospital"
    })
    await asyncio.sleep(1)

    # Step 2: IVR
    ivr_msg = await _llm(
        "You are an insurance company IVR system. Generate a realistic short IVR greeting.",
        "Generate a realistic IVR greeting for Pacific Shield Insurance claims department. 2 sentences max.",
        temperature=0.6
    ) or "Thank you for calling Pacific Shield Insurance. For claims, press 1. For prior authorization, press 2."
    await broadcast("insurance_ivr", {
        "call_id": call_id,
        "speaker": "ivr",
        "message": ivr_msg,
    })
    await asyncio.sleep(1)

    nav_msg = await _llm(
        "You are a hospital AI agent calling an insurance company. Sound professional and efficient.",
        f"You just heard an IVR menu. Say you're calling about a prior authorization claim for patient {patient_name}. One sentence.",
        temperature=0.7
    ) or f"I'm calling regarding a prior authorization claim for patient {patient_name}, please transfer me to claims."
    logger.info("[3-PHASE] nav_msg: %s", nav_msg[:80] if nav_msg else "EMPTY")
    await broadcast("insurance_agent_speaks", {
        "call_id": call_id,
        "speaker": "hospital",
        "message": nav_msg,
    })
    await asyncio.sleep(1)

    hold_msg = await _llm(
        "You are an insurance company IVR hold system.",
        "Generate a realistic hold message. Include estimated wait time. 2 sentences.",
        temperature=0.5
    ) or "Please hold while we transfer you to the next available agent. Your estimated wait time is 2 minutes."
    await broadcast("insurance_hold", {
        "call_id": call_id,
        "speaker": "ivr",
        "message": hold_msg,
    })
    await asyncio.sleep(1)

    pickup_msg = await _llm(
        "You are George, a male insurance claims agent at Pacific Shield Insurance. Sound professional and efficient.",
        "Greet a hospital billing coordinator who has been on hold. Say your name is George and your department. 1-2 sentences.",
        temperature=0.8
    ) or "Thank you for holding. This is George from Pacific Shield Insurance, claims department. How can I assist you today?"
    await broadcast("insurance_connected", {
        "call_id": call_id,
        "speaker": "insurance",
        "message": pickup_msg,
    })
    await asyncio.sleep(1)

    # Hospital agent asks the specific question FIRST
    explain_msg = await _llm(
        "You are a hospital billing coordinator calling an insurance company. Be specific and direct.",
        f"Ask Sarah about the prior authorization denial for patient {patient_name}. Ask for: the denial reason code, the appeal deadline, and whether a Peer-to-Peer review is available. 2 sentences.",
        temperature=0.7
    ) or f"Hi Sarah, I'm calling about a prior authorization denial for patient {patient_name}. Can you confirm the denial reason code, the appeal deadline, and whether a Peer-to-Peer review is an option?"
    logger.info("[3-PHASE] explain_msg: %s", explain_msg[:60] if explain_msg else "EMPTY")
    await broadcast("insurance_agent_speaks", {
        "call_id": call_id,
        "speaker": "hospital",
        "message": explain_msg,
    })
    await asyncio.sleep(1)

    # Insurance agent Sarah answers the specific question
    insurance_response = await _llm(
        "You are George, a male insurance claims agent at Pacific Shield Insurance answering a hospital billing coordinator's specific question about a claim denial. Be factual and helpful.",
        f"The hospital coordinator asked about {patient_name}'s denial. Claim data: {claim_answer}. "
        f"Answer their question directly as George: confirm CO-4 denial code (no prior auth), state the 30-day appeal deadline, confirm Peer-to-Peer review is available. "
        f"Speak professionally to the hospital coordinator. 3 sentences. Your name is George.",
        temperature=0.75
    ) or f"Yes, I can confirm that claim was denied under denial code CO-4 — prior authorization was not obtained before the procedure. Your hospital has 30 days from the denial date to submit a formal appeal. The attending physician can also request a Peer-to-Peer clinical review by calling our medical management line at any time."
    logger.info("[3-PHASE] insurance_response: %s", insurance_response[:60] if insurance_response else "EMPTY")
    await broadcast("insurance_response", {
        "call_id":        call_id,
        "speaker":        "insurance",
        "agent_response": insurance_response,
        "claim_status":   "DENIED_NO_PA",
        "summary":        "Prior authorization not obtained",
    })
    await asyncio.sleep(1)

    confirm_msg = await _llm(
        "You are a hospital AI agent wrapping up a call with an insurance company.",
        "Thank the insurance agent and confirm you have the information needed. Say you'll follow up on the appeal. 1-2 sentences.",
        temperature=0.7
    ) or "Thank you Sarah, I have all the information I need. We will submit the appeal and follow up with the patient."
    await broadcast("insurance_agent_speaks", {
        "call_id": call_id,
        "speaker": "hospital",
        "message": confirm_msg,
    })
    await asyncio.sleep(1)

    # ── Phase 3: Build natural callback message ───────────────────────────
    callback_msg = await _llm(
        "You are a hospital AI assistant calling a patient back with insurance information. Sound caring and clear.",
        f"Call back {patient_name} to explain what you found out from Pacific Shield Insurance. "
        f"Insurance said: {insurance_response}. "
        f"Also share: {claim_answer}. "
        f"Be warm, clear, and concise. Explain what happened and what the patient should do next. 4-5 sentences.",
        temperature=0.7
    )
    full_callback = f"Hello, this is your hospital's automated assistant calling back for {patient_name}. {callback_msg}"

    await broadcast("callback_initiated", {
        "call_id":          call_id,
        "patient_name":     patient_name,
        "callback_number":  callback_number,
        "callback_message": full_callback,
        "claim_status":     "DENIED_NO_PA",
    })

    # Make the actual Twilio callback
    callback_result = await _call_patient_back(callback_number, full_callback)

    logger.info("[3-PHASE] Complete for %s — callback: %s", patient_name, callback_result.get("status"))

    return {
        "patient_name":       patient_name,
        "inquiry_type":       inquiry_type,
        "insurance_response": insurance_response,
        "callback_message":   full_callback,
        "callback_result":    callback_result,
        "phases_completed":   3,
    }


async def _call_patient_back(callback_number: str, message: str) -> dict:
    if not TWILIO_SID or not TWILIO_TOKEN or not TWILIO_FROM:
        logger.info("[3-PHASE] No Twilio config — logging callback only")
        return {"status": "logged_only"}
    try:
        from twilio.rest import Client
        from twilio.twiml.voice_response import VoiceResponse
        twiml = VoiceResponse()
        twiml.say(message, voice="Polly.Joanna")
        twiml.say("Thank you. Goodbye.", voice="Polly.Joanna")
        client = Client(TWILIO_SID, TWILIO_TOKEN)
        call   = client.calls.create(twiml=str(twiml), to=callback_number, from_=TWILIO_FROM)
        logger.info("[3-PHASE] Callback CallSid=%s", call.sid)
        return {"status": "initiated", "call_sid": call.sid}
    except Exception as e:
        logger.error("[3-PHASE] Callback failed: %s", e)
        return {"status": "failed", "error": str(e)}
